"""feat: lead model

Revision ID: ee7c10962e55
Revises: 118ffda30050
Create Date: 2026-02-24 10:04:13.049627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ee7c10962e55'
down_revision: Union[str, None] = '118ffda30050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = inspect(bind)
    tables = set(insp.get_table_names())

    if "lead" not in tables:
        op.create_table(
            'lead',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=128), nullable=False),
            sa.Column('phone', sa.String(length=32), nullable=False),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('status', sa.String(length=32), server_default='new', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        cols = {c["name"] for c in insp.get_columns("lead")}
        if "note" not in cols:
            op.add_column("lead", sa.Column("note", sa.Text(), nullable=True))
        if "status" not in cols:
            op.add_column(
                "lead",
                sa.Column("status", sa.String(length=32), server_default="new", nullable=False),
            )
        if "created_at" not in cols:
            op.add_column(
                "lead",
                sa.Column(
                    "created_at",
                    sa.DateTime(timezone=True),
                    server_default=sa.func.now(),
                    nullable=False,
                ),
            )
        if "updated_at" not in cols:
            op.add_column(
                "lead",
                sa.Column(
                    "updated_at",
                    sa.DateTime(timezone=True),
                    server_default=sa.func.now(),
                    nullable=True,
                ),
            )

    lead_indexes = {ix["name"] for ix in insp.get_indexes("lead")}
    if op.f('ix_lead_id') not in lead_indexes:
        op.create_index(op.f('ix_lead_id'), 'lead', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_id'), table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###
